### ISSUE TITLE
大佬请教一下geodata和ruleset的区别

### ISSUE THREAD

**Issue by psychosispy** [DustinWin/clash-tutorials#14]
目前使用的是ruleset，发现这两种方式域名列表都一样，比较疑惑，请教下大佬
1.geodata是不是只是把那些规则打包成database，看别人说geodata运行效率更高，是真的吗？
2.geodata是否可以补充ruleset，以及DOMAIN规则搭配使用呢?
3.clashmeta的proxy/rule_provider有办法走代理更新吗,是不是只能在rules里加上相应的domain规则

另外，建议再补充一些proxy的上游规则，目前使用的黑名单模式，有一些网站还是无法覆盖，感谢大佬

**Comment by DustinWin** [comment]
1. 效率差不多，感知不强
2. 可以，geodata 与 ruleset 相比，geodata 不能按需添加，所以 ruleset 更灵活
3. 据我所知，只能指定 DNS 服务器

proxy 上游已经添加主流的源，已经尽量包含需要代理的内容，你可以自行在 `rules` 里添加需要走代理的网站
