### ISSUE TITLE
根据您的教程自己制作订阅链接但是节点获取不到

### ISSUE THREAD

**Issue by Vincent-Liu0123** [DustinWin/clash-tutorials#2]
根据您的教程。填了模版获取不到节点
![cbb466456f8888391f5a8114ea1d7e7c](https://github.com/DustinWin/clash-tutorials/assets/67837156/90a5526a-c8fb-4941-b3b9-dd0c7b46d6b4)

**Comment by Vincent-Liu0123** [comment]
救救孩子吧。整一天了。

**Comment by Vincent-Liu0123** [comment]
> > 
> 
> 链接添加后缀 `&flag=clash`。

加了，我的节点是我自己的vps，然后用了vmess，用clash转换，节点获取失败。但是我用了机场的clash加后缀后可以正常获取。

**Comment by DustinWin** [comment]
> > > 
> > 
> > 
> > 链接添加后缀 `&flag=clash`。
> 
> 加了，我的节点是我自己的vps，然后用了vmess，用clash转换，节点获取失败。但是我用了机场的clash加后缀后可以正常获取。

浏览器通过直连打开该链接可以打开吗？内容有吗？

**Comment by DustinWin** [comment]
请优先使用 Meta 内核。
