### ISSUE TITLE
导入yaml配置报错

### ISSUE THREAD

**Issue by youfun** [DustinWin/clash-tutorials#3]
yaml: line 16: did not find expected key
configuration file /tmp/ShellClash/clash_config_root.yaml test failed

<img width="333" alt="image" src="https://github.com/DustinWin/clash-tutorials/assets/3973573/6cf25916-17f2-4549-8138-03ae5aa43770">

最新的meta1.1.5.1 内核

配置如下：
就是教程的模板去掉机场筛选节点

``
proxy-providers:
  # 获取机场订阅链接内的所有节点
  🛫 我的机场 1:
    type: http
    # 机场订阅链接，使用 Clash 链接
    url: "https:/&flag=clash"
    path: ./proxies/airport1.yaml
    interval: 43200
    # 初步筛选需要的节点，可有效减轻路由器压力，支持正则表达式，不筛选可删除此配置项
    health-check:
      enable: true
      # 未选择到当前策略组时，不会进行测试，有多个 proxy-providers 时可使用
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600

  🛫 我的机场 2:
    type: http
    url: "https://&flag=clash"
    path: ./proxies/airport2.yaml
    interval: 43200
    health-check:
      enable: true
      lazy: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600

proxy-groups:
  # 手动选择国家或地区节点；根据 proxy-groups 中（下方）国家或地区的节点名称对 proxies 值进行增删改，须一一对应
  - {name: 🚀 节点选择, type: select, proxies: [🇭🇰 香港节点, 🇹🇼 台湾节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇸🇬 新加坡节点, 🇺🇸 美国节点]}

  # Speedtest 测速网站：选择“全球直连”为测试本地网络速度（运营商网络速度），可选择其它节点用于测试机场节点速度
  - {name: 📈 网络测速, type: select, proxies: [🎯 全球直连, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇸🇬 新加坡节点, 🇺🇸 美国节点]}

  - {name: 🐟 漏网之鱼, type: select, proxies: [🚀 节点选择, 🎯 全球直连]}

  - {name: ⚡ 直连域名, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}

  - {name: 🪜 代理域名, type: select, proxies: [🚀 节点选择, 🎯 全球直连]}

  - {name: 🎮 国区游戏, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}

  - {name: Ⓜ️ Microsoft 中国, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}

  - {name: 🗽 Google 中国, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}

  - {name: 🍎 Apple 中国, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}

  - {name: 🇨🇳 国内 IP, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}

  - {name: ✈️ Telegram IP, type: select, proxies: [🚀 节点选择]}

  - {name: 🏠 私有网络, type: select, proxies: [🎯 全球直连]}

  - {name: ⛔️ 广告域名, type: select, proxies: [🛑 全球拦截]}

  - {name: 🎯 全球直连, type: select, proxies: [DIRECT]}

  - {name: 🛑 全球拦截, type: select, proxies: [REJECT]}

  # -----------------国家或地区节点----------------------

  # 自动选择节点，即按照 url 测试结果使用延迟最低的节点；测试后容差大于 100ms 才会切换到延迟低的那个节点；未选择到当前策略组时不会进行延迟测试；筛选出“香港”节点，支持正则表达式
  - {name: 🇭🇰 香港节点, type: url-test, tolerance: 100, lazy: true, use: [🛫 我的机场 1, 🛫 我的机场 2], filter: "香港"}

  - {name: 🇹🇼 台湾节点, type: url-test, tolerance: 100, lazy: true, use: [🛫 我的机场 1, 🛫 我的机场 2], filter: "台湾"}

  - {name: 🇯🇵 日本节点, type: url-test, tolerance: 100, lazy: true, use: [🛫 我的机场 1, 🛫 我的机场 2], filter: "日本"}

  - {name: 🇰🇷 韩国节点, type: url-test, tolerance: 100, lazy: true, use: [🛫 我的机场 1, 🛫 我的机场 2], filter: "韩国"}

  - {name: 🇸🇬 新加坡节点, type: url-test, tolerance: 100, lazy: true, use: [🛫 我的机场 1, 🛫 我的机场 2], filter: "新加坡"}

  - {name: 🇺🇸 美国节点, type: url-test, tolerance: 100, lazy: true, use: [🛫 我的机场 1, 🛫 我的机场 2], filter: "美国"}

rules:
  # 自定义规则优先放前面
  - GEOSITE,category-ads-all,⛔️ 广告域名
  # 若使用 Clash Verge，为过滤 P2P 流量（BT 下载），可添加一条 DST-PORT 规则
  - DST-PORT,6881-6889,🎯 全球直连
  - GEOSITE,private,🏠 私有网络
  - GEOSITE,speedtest,📈 网络测速
  - GEOSITE,microsoft@cn,Ⓜ️ Microsoft 中国
  - GEOSITE,apple-cn,🍎 Apple 中国
  - GEOSITE,google-cn,🗽 Google 中国
  - GEOSITE,category-games@cn,🎮 国区游戏
  - GEOSITE,geolocation-!cn,🪜 代理域名
  - GEOSITE,cn,⚡ 直连域名
  - GEOIP,telegram,✈️ Telegram IP
  - GEOIP,private,🏠 私有网络,no-resolve
  - GEOIP,cn,🇨🇳 国内 IP
  - MATCH,🐟 漏网之鱼

**Comment by DustinWin** [comment]
在报错时将 */tmp/ShellClash/clash_config_root.yaml* 文件发出来。

**Comment by youfun** [comment]
先用自带的在线转化，然后再切换回你给的这道yaml就好了。猜测可能是机场链接被拦截了。

**Comment by DustinWin** [comment]
> 先用自带的在线转换，然后再切换回你给的这套yaml配置就好了。猜测可能是机场链接被拦截了。

好的。
