### ISSUE TITLE
DNS分流方案里能否实现国内4/6双栈 国外dns只解析ipv4地址

### ISSUE THREAD

**Issue by gzxiexl** [DustinWin/clash-tutorials#4]
[ShellClash](https://github.com/juewuy/ShellClash) 使用 [Clash.Meta 内核](https://github.com/MetaCubeX/Clash.Meta)进行 DNS 分流教程 geox 方案

谢谢

**Comment by DustinWin** [comment]
> [ShellClash](https://github.com/juewuy/ShellClash) 使用 [Clash.Meta 内核](https://github.com/MetaCubeX/Clash.Meta)进行 DNS 分流教程 geox 方案
> 
> 谢谢
目前光靠 ShellClash 和 Clash.Meta 内核无法实现这个功能。

**Comment by gzxiexl** [comment]
我有个思路就是不知道怎么操作：
mosdns负责分流--国内DNS交给 223.5.5.5 实现 ipv4 ipv6 双栈----国外dns 给 clash 的 dns 服务（ipv6 不解析）

**Comment by DustinWin** [comment]
> 我有个思路就是不知道怎么操作： mosdns负责分流--国内DNS交给 223.5.5.5 实现 ipv4 ipv6 双栈----国外dns 给 clash 的 dns 服务（ipv6 不解析）

我没有去折腾 mosdns。

**Comment by muccichung** [comment]
mosdns+shellclash支持来一个，自己不会配置...

**Comment by DustinWin** [comment]
> mosdns+shellclash支持来一个，自己不会配置...

对我来说，fake-ip 已经够用了，没有折腾 mosdns 的计划。
