### ISSUE TITLE
小米7000只有16M的存储空间

### ISSUE THREAD

**Issue by nnn149** [DustinWin/clash-tutorials#5]
请问小米7000解锁完ssh只有16M的存储空间，能装得下shellclash和AdGuardHome吗？我你示例用的是Redmi AX6000，也是128MB的闪存，是剩余空间比较大吗?

**Comment by nnn149** [comment]
装完shellclash只有7.6M了
![image](https://github.com/DustinWin/clash-tutorials/assets/23712868/89cf6ae7-11ed-42e2-9d30-f4b4a2730b83)

**Comment by DustinWin** [comment]
> 装完shellclash只有7.6M了 ![image](https://user-images.githubusercontent.com/23712868/282827643-89cf6ae7-11ed-42e2-9d30-f4b4a2730b83.png)
7000 的分区太小了，建议只安装 ShellClash，且规则不要弄太多。这是红米 6000 的分区：
![QQ截图20231115123145](https://github.com/DustinWin/clash-tutorials/assets/45238096/2004d159-82d0-4e7f-b2e3-3874020d7e98)

**Comment by nnn149** [comment]
我去，都是128M的闪存，怎么红米ax6000空间大一倍！

**Comment by nnn149** [comment]
小米7000可以外接USB硬盘，是否可以把AdGuardHome或ShellClash装到U盘上？或者AdGuardHome可以装到Docker里吗？装到Docker后是否还能配合ShellClash，不知大佬是否有研究

**Comment by DustinWin** [comment]
> 小米7000可以外接USB硬盘，是否可以把AdGuardHome或ShellClash装到U盘上？或者AdGuardHome可以装到Docker里吗？装到Docker后是否还能配合ShellClash，不知大佬是否有研究

都安装在 U 盘是可以互相配合的。
