### ISSUE TITLE
ShellClash配置-geox方案>>>>导入Clash.Meta内核错误

### ISSUE THREAD

**Issue by Old-line** [DustinWin/clash-tutorials#6]
![image](https://github.com/DustinWin/clash-tutorials/assets/30979454/f40e591e-5b64-448e-a9ab-5fb730b5a56e)

你好，我导入内核失败了，导入路由规则文件也有同样的错误。
初步判定可能是内核链接和规则链接被墙的原因，但我在Dashboard 中将路由改为了全局代理发现并没有什么用。请问一下这种情况如何解决。

PS.我的路由器是红米AX6000

**Comment by DustinWin** [comment]
将链接中的 `cdn` 改成 `fastly` 试试。

**Comment by Old-line** [comment]
非常感谢，确实解决了。
建议有相同问题的朋友把“三、 添加定时任务”内连接中的 cdn 也改成 fastly
