### ISSUE TITLE
process name无效

### ISSUE THREAD

**Issue by WuYang09661** [DustinWin/clash-tutorials#7]
![Screenshot_2023-11-30-10-17-10-125_com github met](https://github.com/DustinWin/clash-tutorials/assets/81788651/99d4dc25-7991-469a-8a09-548e54f4803f)
请问，mingming明明已经把process name拉到最上面，但是还是会有遗漏的是为什么，折腾好久了没找到与原因，process mode也调试过，strict always off都试过，都没啥用
明明已经识别了process了，还是有泄漏出去走漏网之鱼的，tiktok我并未使用domain keyword
但是我在使用afreecatv时，虽然我添加了domain keyword，但是优先级是在process name 之下的，结果还是先走了domain keyword，而且我删除了那条afreecatv 的keyword之后，又能走process name了

**Comment by DustinWin** [comment]
你用的 ShellClash 还是 CMFA？

**Comment by WuYang09661** [comment]
> 你用的 ShellClash 还是 CMFA？

cmfa

**Comment by DustinWin** [comment]
> > 你用的 ShellClash 还是 CMFA？
> 
> cmfa

这个你得给 CMFA 提 issues 了。
